apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name | quote  }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      nodePort: {{ .nodePort }}
    {{- end }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
