apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  serviceName: {{ include "fullname" . }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        helm-revision: "{{ .Release.Revision }}"
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      nodeName: {{ .Values.nodeName }}
      terminationGracePeriodSeconds: 60
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*      serviceAccountName: {{ include "serviceAccountName" . }}*/}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.persistence }}
          volumeMounts:
            {{- range .Values.volumes }}
            - name: {{ .name | quote }}
              mountPath: {{ .mountPath | quote }}
            {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.workingDir }}
          command: {{- toYaml .Values.command | nindent 12 }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name | quote }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.livenessProbeEnabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbeEnabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.envs | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence }}
  volumeClaimTemplates:
  {{- range .Values.persistences }}
  - metadata:
      name: {{ .name | quote }}
    spec:
      storageClassName: {{ .storageClassName | quote }}
      accessModes:
        - {{ .accessMode | quote }}
      resources:
        requests:
          storage: {{ .size | quote }}
  {{- end }}
  {{- end }}
